version: '3.7'
services:
  grpc_service:
    build:
      context: '.'
      dockerfile: Dockerfile
    image: kenesparta/tk_grpc_service
    container_name: grpc_service
    restart: "no"
    ports:
      - "8085:8085"
